name: ci

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ['3.2.2', 'jruby-10.0.6.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Check bundle
        run: |
          bundle check
